export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAIL = "ORDER_FAIL"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
export const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS"
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"


export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET"


export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET"






export const CLEAR_ERRORS = "CLEAR_ERRORS"
