export const All_PRODUCT_REQUEST = "All_PRODUCT_REQUEST";
export const All_PRODUCT_SUCCESS = "All_PRODUCT_SUCCESS";
export const All_PRODUCT_FAIL = "All_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PRODUCT_DETAILS_REQUEST = "All_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "All_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "All_DETAILS_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEWREQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEWSUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEWFAIL";
export const ADD_REVIEW_RESET = "ADD_REVIEW_ADMIN";

export const PRODUCT_ADMIN_REQUEST = "PRODUCT_ADMIN_REQUEST";
export const PRODUCT_ADMIN_SUCCESS = "PRODUCT_ADMIN_SUCCESS";
export const PRODUCT_ADMIN_FAIL = "PRODUCT_ADMIN_FAIL";

export const PRODUCT_DELETE_REQUEST = "All_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "All_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "All_DELETE_FAIL";
export const  PRODUCT_DELETE_RESET = " PRODUCT_DELETE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const  PRODUCT_UPDATE_RESET = " PRODUCT_UPDATE_RESET";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";



