export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

export const REG_USER_REQUEST = "REG_USER_REQUEST"
export const REG_USER_SUCCESS = "REG_USER_SUCCESS"
export const REG_USER_FAIL = "REG_USER_FAIL"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"


export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET"


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS= "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL= "FORGOT_PASSWORD_FAIL"


export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS= "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL= "RESET_PASSWORD_FAIL"

export const ALL_ADMIN_USER_REQUEST = "ALL_ADMIN_USER_REQUEST"
export const ALL_ADMIN_USER_SUCCESS = "ALL_ADMIN_USER_SUCCESS"
export const ALL_ADMIN_USER_FAIL = "ALL_ADMIN_USER_FAIL"

export const GET_ADMIN_USER_REQUEST = "GET_ADMIN_USER_REQUEST"
export const GET_ADMIN_USER_SUCCESS = "GET_ADMIN_USER_SUCCESS"
export const GET_ADMIN_USER_FAIL = "GET_ADMIN_USER_FAIL"

export const UPDATE_ADMIN_USER_REQUEST = "UPDATE_ADMIN_USER_REQUEST"
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS"
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL"
export const UPDATE_ADMIN_USER_RESET = "UPDATE_ADMIN_USER_RESET"

export const DELETE_ADMIN_USER_REQUEST = "DELETE_ADMIN_USER_REQUEST"
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS"
export const DELETE_ADMIN_USER_FAIL = "DELETE_ADMIN_USER_FAIL"
export const DELETE_ADMIN_USER_RESET = "DELETE_ADMIN_USER_RESET"

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST"
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS"
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL"

export const DELETE_REVIEWS_REQUEST = "DELETE_REVIEWS_REQUEST"
export const DELETE_REVIEWS_SUCCESS = "DELETE_REVIEWS_SUCCESS"
export const DELETE_REVIEWS_FAIL = "DELETE_REVIEWS_FAIL"
export const DELETE_REVIEWS_RESET = "DELETE_REVIEWS_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
